<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<PackageId>SEM7AC.SystemInfo</PackageId>
		<Version>1.0.0</Version>
		<Authors>SEM7AC</Authors>
		<Company>SEM7AC</Company>
		<Product>SEM7AC.SystemInfo</Product>

		<Description>Lightweight, fast, zero-dependency system information provider for .NET. CPU, Memory, Storage, OS.</Description>
		<PackageTags>system info diagnostics cpu memory storage os windows</PackageTags>

		<RepositoryUrl>https://github.com/SEM7AC/SEM7AC.SystemInfo</RepositoryUrl>
		<PackageProjectUrl>https://github.com/SEM7AC/SEM7AC.SystemInfo</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<!-- REQUIRED FOR NUGET README -->
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<!-- REQUIRED TO PACK README INTO THE NUPKG -->
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>
